services:
  waline:
    container_name: waline
    image: lizheming/waline:1.41.3
    restart: always
    ports:
      - "127.0.0.1:8360:8360"
    env_file:
      - .env
    volumes:
      - /opt/waline/data:/app/data
      - ./config.js:/app/node_modules/@waline/vercel/config.js:ro
