server {
    listen 80;
    listen [::]:80;
    server_name soloeternity.me;

    root /var/www/blog/current;
    index index.html;

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }
}
