services:
  caddy2:
    build: .
    image: caddy2-custom
    container_name: caddy
    restart: unless-stopped
    env_file: .env
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    networks:
      - seaweedfs
      - openlist
      - lobehub
      - waline_default
      - memos_default
      - frps
      - umami_default
      - chevereto_default
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 7000:7000
    volumes:
      - ./conf:/etc/caddy:ro
      - /var/www:/var/www:ro
      - data:/data
      - config:/config
    tmpfs:
      - /tmp:size=16m,mode=1777

networks:
  seaweedfs:
    external: true
  openlist:
    external: true
  lobehub:
    external: true
  waline_default:
    external: true
  memos_default:
    external: true
  frps:
    external: true
  umami_default:
    external: true
  chevereto_default:
    external: true

volumes:
  data:
    name: caddy-data
  config:
    name: caddy-config
